Repository OCA/pms, pull requests merged in 2021-06, with the labels that each got.

#12 [14.0] [FIX] pms: fix properties error board_service_room_type
  pms/models/pms_board_service_room_type.py
  pms/tests/test_pms_board_service_room_type.py
Labels: bot is merging ⏳

#9 [14.0] [IMP] pms manage pricelist board services
  pms/i18n/es.po
  pms/i18n/pms.pot
  pms/models/pms_board_service_room_type.py
  pms/models/pms_service.py
  pms/models/product_pricelist.py
  pms/models/product_pricelist_item.py
  pms/tests/test_pms_pricelist.py
  pms/tests/test_pms_pricelist_priority.py
  pms/tests/test_pms_wizard_folio.py
  pms/tests/test_pms_wizard_massive_changes.py
  pms/views/pms_availability_plan_rule_views.xml
  pms/views/product_pricelist_item_views.xml
  pms/views/product_pricelist_views.xml
  pms/wizards/wizard_massive_changes.py
  pms/wizards/wizard_massive_changes.xml
Labels: bot is merging ⏳

#17 [14.0][REF] pms: availability plan wizard massive changes extensibility
  pms/wizards/wizard_massive_changes.py
Labels: bot is merging ⏳

#14 [WIP] [14.0] [REF] Refactor common tests
  pms/models/res_partner.py
  pms/tests/__init__.py
  pms/tests/test_pms_board_service.py
  pms/tests/test_pms_board_service_line.py
  pms/tests/test_pms_board_service_room_type.py
  pms/tests/test_pms_board_service_room_type_line.py
  pms/tests/test_pms_room.py
  pms/tests/test_pms_room_type.py
  pms/tests/test_pms_sale_channel.py
  pms/tests/test_pms_wizard_massive_changes.py
  pms/tests/test_product_template.py
Labels: bot is merging ⏳, work in progress

#21 [14.0][FIX] pms: wizard massive changes same rule dates
  pms/wizards/wizard_massive_changes.py
Labels: approved, bot is merging ⏳

#16 [IMP][14.0] pms to assign reservation flow
  pms/models/pms_reservation.py
  pms/models/pms_reservation_line.py
  pms/tests/test_pms_reservation.py
  pms/views/pms_reservation_views.xml
Labels: bot is merging ⏳

#18 [REF]pms: Refactor pricelist tests
  pms/tests/__init__.py
  pms/tests/test_pms_pricelist.py
  pms/tests/test_pms_pricelist_priority.py
  pms/tests/test_pms_pricelist_settings.py
  pms/tests/test_pms_reservation_prices.py
Labels: bot is merging ⏳

#15 [IMP][14.0] pms refact folio tests
  pms/models/pms_folio.py
  pms/models/pms_reservation.py
  pms/models/pms_reservation_line.py
  pms/tests/test_pms_folio.py
  pms/tests/test_pms_folio_invoice.py
  pms/tests/test_pms_folio_sale_line.py
  pms/tests/test_pms_reservation.py
Labels: bot is merging ⏳

#20 [14.0] [IMP] pms_l10n_es add traveller report
  pms_l10n_es/__manifest__.py
  pms_l10n_es/data/cron_jobs.xml
  pms_l10n_es/data/queue_data.xml
  pms_l10n_es/data/queue_job_function_data.xml
  pms_l10n_es/i18n/pms_l10n_es.pot
  pms_l10n_es/models/__init__.py
  pms_l10n_es/models/pms_log_institution_traveller_report.py
  pms_l10n_es/models/pms_property.py
  pms_l10n_es/security/ir.model.access.csv
  pms_l10n_es/views/pms_log_institution_traveller_report_views.xml
  pms_l10n_es/views/pms_property_views.xml
  pms_l10n_es/wizards/traveller_report.py
  pms_l10n_es/wizards/traveller_report.xml
Labels: bot is merging ⏳

#13 [14.0][IMP] Invoicing flow
  pms/models/folio_sale_line.py
  pms/models/pms_folio.py
  pms/models/pms_reservation.py
  pms/models/pms_service.py
  pms/views/pms_folio_views.xml
  pms/wizards/folio_make_invoice_advance.py
Labels: bot is merging ⏳

#11 Refactoring checkin flow
  pms/__manifest__.py
  pms/data/pms_data.xml
  pms/data/traveller_report_paperformat.xml
  pms/models/__init__.py
  pms/models/pms_checkin_partner.py
  pms/models/pms_property.py
  pms/models/pms_reservation.py
  pms/models/res_company.py
  pms/models/res_partner.py
  pms/models/res_partner_id_number.py
  pms/report/traveller_report_action.xml
  pms/tests/test_pms_checkin_partner.py
  pms/tests/test_pms_res_users.py
  pms/tests/test_pms_reservation.py
  pms/views/pms_checkin_partner_views.xml
  pms/views/pms_property_views.xml
  pms/views/pms_reservation_views.xml
  pms/views/res_company_views.xml
  pms/views/traveller_report_template.xml
  pms_l10n_es/__manifest__.py
  pms_l10n_es/data/pms_data.xml
  pms_l10n_es/models/__init__.py
  pms_l10n_es/models/pms_checkin_partner.py
  pms_l10n_es/models/res_partner.py
  pms_l10n_es/tests/__init__.py
  pms_l10n_es/tests/test_partner.py
  pms_l10n_es/views/pms_checkin_partner_views.xml
  pms_l10n_es/views/res_partner_views.xml
Labels: bot is merging ⏳

#22 [IMP] Compute reservation priority
  pms/data/cron_jobs.xml
  pms/demo/pms_folio.xml
  pms/models/pms_checkin_partner.py
  pms/models/pms_reservation.py
  pms/tests/test_pms_reservation.py
Labels: bot is merging ⏳

#23 [14.0][FIX] pms: error on daily pricelist detection
  pms/models/product_pricelist.py
Labels: bot is merging ⏳

#24 [14.0][IMP] Change font size in checkin report and fix checkin flow
  pms/models/pms_checkin_partner.py
  pms/models/pms_reservation.py
  pms/tests/test_pms_checkin_partner.py
  pms/views/pms_checkin_partner_views.xml
  pms/views/res_partner_views.xml
  pms/views/traveller_report_template.xml
Labels: approved, bot is merging ⏳

#25 [14.0][FIX] pms: minor bugfixes
  pms/models/folio_sale_line.py
  pms/models/pms_folio.py
  pms/views/pms_folio_views.xml
Labels: approved, bot is merging ⏳

#29 [FIX]pms: fixed mobile and email fields when there are incongruences …
  pms/models/res_partner.py
Labels: bot is merging ⏳

#30 [14.0][FIX+IMP] pms: Minor bugfixes and improvements
  pms/models/pms_availability.py
  pms/models/pms_folio.py
  pms/models/pms_reservation.py
  pms/models/pms_room_type.py
  pms/tests/test_pms_reservation.py
  pms/views/pms_reservation_views.xml
Labels: bot is merging ⏳

#32 [14-0][IMP+REF] pms: Allow force overbooking when no availability
  pms/models/pms_reservation_line.py
Labels: bot is merging ⏳
