Repository OCA/pms, pull requests merged in 2021-07, with the labels that each got.

#31 14.0 Refactor reservation tests and refactor computes in reservation and folio
  pms/models/pms_folio.py
  pms/models/pms_reservation.py
  pms/models/res_partner.py
  pms/tests/test_pms_reservation.py
  pms/views/pms_reservation_views.xml
  pms/views/reservation_portal_templates.xml
Labels: bot is merging ⏳

#33 [WIP]14.0 pms refactor tests
  pms/tests/test_pms_availability_plan_rules.py
  pms/tests/test_pms_folio_sale_line.py
Labels: bot is merging ⏳

#27 [FIX] Fix partner data view calls from reservation and folio
  pms/models/pms_checkin_partner.py
  pms/models/pms_folio.py
  pms/models/pms_reservation.py
Labels: bot is merging ⏳

#36 [RFC] Availability and free rooms
  pms/models/pms_availability_plan.py
  pms/models/pms_property.py
  pms/models/pms_reservation.py
  pms/models/pms_reservation_line.py
  pms/models/pms_room.py
  pms/models/pms_room_type.py
  pms/tests/test_pms_availability_plan_rules.py
  pms/tests/test_pms_booking_engine.py
  pms/wizards/pms_booking_engine.py
  pms/wizards/wizard_split_join_swap_reservation.py
Labels: approved, bot is merging ⏳

#34 [14.0][IMP] Compute discounts on cancellation flow
  pms/models/pms_reservation.py
  pms/models/pms_reservation_line.py
  pms/models/pms_service.py
  pms/models/pms_service_line.py
  pms/tests/test_pms_reservation.py
  pms/views/pms_reservation_views.xml
Labels: approved, bot is merging ⏳

#37 14.0 pms refactor room_type_class and wizard_split_join_swap_reservation tests
  pms/tests/test_pms_room_type_class.py
  pms/tests/test_pms_wizard_split_join_swap_reservation.py
Labels: approved, bot is merging ⏳, ready to merge

#41 [REF] Refactor pms_booking_engine tests
  pms/tests/test_pms_booking_engine.py
Labels: bot is merging ⏳

#44 [IMP]pms: Swap source and target complete reservations between dates
  pms/tests/test_pms_wizard_split_join_swap_reservation.py
  pms/wizards/wizard_split_join_swap_reservation.py
Labels: bot is merging ⏳, needs review

#42 [14.0][FIX] pms: wrong plan avail when real avail is zero
  pms/models/pms_availability_plan_rule.py
  pms/tests/test_pms_availability_plan_rules.py
Labels: bot is merging ⏳

#46 [14.0][FIX] Fix board service price and discount in booking engine
  pms/models/pms_service_line.py
  pms/tests/test_pms_booking_engine.py
  pms/wizards/pms_booking_engine.py
Labels: bot is merging ⏳

#45 [FIX]: Fix check_date_order, check_checkin_datetime and cancelatio…
  pms/models/pms_reservation.py
  pms/tests/test_pms_reservation.py
Labels: bot is merging ⏳

#47 [IMP]pms:Added a multiproperty test file
  pms/tests/__init__.py
  pms/tests/test_pms_amenity.py
  pms/tests/test_pms_availability_plan_rules.py
  pms/tests/test_pms_board_service_line.py
  pms/tests/test_pms_board_service_room_type.py
  pms/tests/test_pms_board_service_room_type_line.py
  pms/tests/test_pms_folio.py
  pms/tests/test_pms_multiproperty.py
  pms/tests/test_pms_pricelist.py
  pms/tests/test_pms_reservation.py
  pms/tests/test_pms_room.py
Labels: bot is merging ⏳

#38 [FIX] pms: booking engine qty rooms from n to 0
  pms/tests/test_pms_booking_engine.py
  pms/wizards/pms_booking_engine.py
Labels: bot is merging ⏳

#50 [REF]pms: refactor pms_folio_invoice tests
  pms/tests/test_pms_folio_invoice.py
Labels: bot is merging ⏳

#35 [14.0] [IMP] - Generate INE (National Institute of Statistics of Spain) file.
  oca_dependencies.txt
  pms/models/pms_reservation.py
  pms/models/pms_reservation_line.py
  pms/models/pms_room.py
  pms/models/pms_service.py
  pms/tests/test_pms_reservation.py
  pms/views/pms_property_views.xml
  pms/views/pms_reservation_views.xml
  pms_l10n_es/__manifest__.py
  pms_l10n_es/data/pms.ine.tourism.type.category.csv
  pms_l10n_es/data/res.country.state.csv
  pms_l10n_es/models/__init__.py
  pms_l10n_es/models/pms_ine_tourism_type_category.py
  pms_l10n_es/models/pms_property.py
  pms_l10n_es/models/pms_room.py
  pms_l10n_es/models/res_country_state.py
  pms_l10n_es/security/ir.model.access.csv
  pms_l10n_es/tests/__init__.py
  pms_l10n_es/tests/common.py
  pms_l10n_es/tests/test_wizard_ine.py
  pms_l10n_es/views/pms_ine_tourism_type_category.xml
  pms_l10n_es/views/pms_property_views.xml
  pms_l10n_es/views/pms_room_views.xml
  pms_l10n_es/wizards/__init__.py
  pms_l10n_es/wizards/wizard_ine.py
  pms_l10n_es/wizards/wizard_ine.xml
  requirements.txt
Labels: bot is merging ⏳
