Repository OCA/pms, pull requests merged in 2022-04, with the labels that each got.

#133 [FIX]pms: emails are not auto deleted when they are sent
  pms/models/pms_folio.py
Labels: bot is merging ⏳

#123 [IMP] [14.0] add constraint (reservation type and closure reason type)
  pms/demo/airbnb-logo.jpg
  pms/demo/booking-logo.jpg
  pms/demo/pms_folio.xml
  pms/demo/pms_reservation.xml
  pms/models/pms_folio.py
  pms/models/pms_reservation.py
  pms/tests/test_pms_folio.py
  pms/tests/test_pms_folio_sale_line.py
  pms/tests/test_pms_reservation.py
  pms/views/pms_reservation_views.xml
Labels: approved, bot is merging ⏳

#125 14.0 pms added new checkin partner fields
  pms/__manifest__.py
  pms/controllers/pms_portal.py
  pms/data/cron_jobs.xml
  pms/data/pms_data.xml
  pms/i18n/pms.pot
  pms/models/__init__.py
  pms/models/account_bank_statement.py
  pms/models/account_bank_statement_line.py
  pms/models/account_journal.py
  pms/models/account_move.py
  pms/models/account_move_line.py
  pms/models/account_payment.py
  pms/models/folio_sale_line.py
  pms/models/pms_availability_plan.py
  pms/models/pms_checkin_partner.py
  pms/models/pms_folio.py
  pms/models/pms_property.py
  pms/models/pms_reservation.py
  pms/models/pms_reservation_line.py
  pms/models/res_company.py
  pms/models/res_partner.py
  pms/models/res_partner_id_category.py
  pms/models/res_partner_id_number.py
  pms/report/invoice.xml
  pms/report/pms_folio_templates.xml
  pms/security/ir.model.access.csv
  pms/tests/test_pms_checkin_partner.py
  pms/tests/test_pms_folio_invoice.py
  pms/views/account_bank_statement_views.xml
  pms/views/account_move_views.xml
  pms/views/account_payment_views.xml
  pms/views/pms_checkin_partner_views.xml
  pms/views/pms_folio_views.xml
  pms/views/pms_property_views.xml
  pms/views/precheckin_portal_templates.xml
  pms/views/res_company_views.xml
  pms/views/res_partner_id_category.xml
  pms/views/res_partner_views.xml
  pms/wizards/__init__.py
  pms/wizards/folio_make_invoice_advance.py
  pms/wizards/pms_booking_duplicate.py
  pms/wizards/pms_booking_duplicate_views.xml
  pms/wizards/wizard_folio_changes.py
  pms/wizards/wizard_folio_changes.xml
  pms_l10n_es/__manifest__.py
  pms_l10n_es/data/pms_data.xml
  pms_l10n_es/models/__init__.py
  pms_l10n_es/models/pms_checkin_partner.py
  pms_l10n_es/models/res_partner.py
  pms_l10n_es/models/res_partner_id_number.py
  pms_l10n_es/tests/test_res_partner.py
  pms_l10n_es/tests/test_wizard_ine.py
  pms_l10n_es/tests/test_wizard_traveller_report.py
  pms_l10n_es/views/pms_checkin_partner_views.xml
  pms_l10n_es/views/precheckin_portal_templates.xml
  pms_l10n_es/views/res_partner_id_number_view.xml
  pms_l10n_es/wizards/wizard_ine.py
Labels: bot is merging ⏳

#137 [IMP]pms: Allow to search the journal based on the property of the context.
  pms/models/account_move.py
Labels: bot is merging ⏳

#138 [FIX] Travis not working on v14 new PR.
  .github/workflows/test.yml
  .travis.yml
Labels: bug

#140 [IMP] pms_base
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  README.md
  pms_base/__manifest__.py
Labels: enhancement

#127 [ADD] pms_project
  pms_project/README.rst
  pms_project/__init__.py
  pms_project/__manifest__.py
  pms_project/models/__init__.py
  pms_project/models/pms_property.py
  pms_project/models/project_task.py
  pms_project/readme/CONTRIBUTORS.rst
  pms_project/readme/CREDITS.rst
  pms_project/readme/DESCRIPTION.rst
  pms_project/readme/USAGE.rst
  pms_project/static/description/icon.png
  pms_project/tests/__init__.py
  pms_project/tests/test_project_task.py
  pms_project/views/pms_property_views.xml
  pms_project/views/project_task_views.xml
  setup/pms_project/odoo/addons/pms_project
  setup/pms_project/setup.py
Labels: enhancement, needs review

#128 [ADD] pms_stock
  pms_stock/README.rst
  pms_stock/__init__.py
  pms_stock/__manifest__.py
  pms_stock/models/__init__.py
  pms_stock/models/pms_property.py
  pms_stock/readme/CONFIGURATION.rst
  pms_stock/readme/CONTRIBUTORS.rst
  pms_stock/readme/DESCRIPTION.rst
  pms_stock/readme/USAGE.rst
  pms_stock/static/description/icon.png
  pms_stock/views/pms_property.xml
  setup/pms_stock/odoo/addons/pms_stock
  setup/pms_stock/setup.py
Labels: enhancement, bot is merging ⏳

#92 [ADD] pms_sale
  oca_dependencies.txt
  pms_sale/README.rst
  pms_sale/__init__.py
  pms_sale/__manifest__.py
  pms_sale/data/ir_sequence.xml
  pms_sale/data/pms_stage.xml
  pms_sale/data/product_data.xml
  pms_sale/i18n/es.po
  pms_sale/i18n/pms_sale.pot
  pms_sale/models/__init__.py
  pms_sale/models/account_move.py
  pms_sale/models/account_move_line.py
  pms_sale/models/pms_mail.py
  pms_sale/models/pms_property.py
  pms_sale/models/pms_property_reservation.py
  pms_sale/models/pms_reservation.py
  pms_sale/models/pms_reservation_guest.py
  pms_sale/models/pms_stage.py
  pms_sale/models/pms_team.py
  pms_sale/models/product.py
  pms_sale/models/sale_order.py
  pms_sale/models/sale_order_line.py
  pms_sale/readme/CONFIGURE.rst
  pms_sale/readme/CONTRIBUTORS.rst
  pms_sale/readme/DESCRIPTION.rst
  pms_sale/readme/USAGE.rst
  pms_sale/security/ir.model.access.csv
  pms_sale/static/description/agency_logo.png
  pms_sale/static/description/agency_logo1.png
  pms_sale/static/description/avatar.png
  pms_sale/static/description/icon.png
  pms_sale/static/description/index.html
  pms_sale/static/src/js/pms_configurator_controller.js
  pms_sale/static/src/js/pms_configurator_view.js
  pms_sale/static/src/js/pms_configurator_widget.js
  pms_sale/static/src/js/timeline.js
  pms_sale/static/src/xml/timeline.xml
  pms_sale/tests/__init__.py
  pms_sale/tests/test_account_move.py
  pms_sale/tests/test_pms_property.py
  pms_sale/tests/test_pms_reservation.py
  pms_sale/views/account_move.xml
  pms_sale/views/assets.xml
  pms_sale/views/menu.xml
  pms_sale/views/pms_mail_views.xml
  pms_sale/views/pms_property.xml
  pms_sale/views/pms_property_reservation.xml
  pms_sale/views/pms_reservation_guest_views.xml
  pms_sale/views/pms_reservation_views.xml
  pms_sale/views/pms_team_views.xml
  pms_sale/views/product_views.xml
  pms_sale/views/sale_order_views.xml
  pms_sale/wizards/__init__.py
  pms_sale/wizards/account_payment_register.py
  pms_sale/wizards/pms_configurator.py
  pms_sale/wizards/pms_configurator_views.xml
  setup/pms_sale/odoo/addons/pms_sale
  setup/pms_sale/setup.py
Labels: enhancement, needs review

#141 [IMP] pms_account
  pms_account/__manifest__.py
Labels: enhancement

#126 [ADD] pms_purchase
  pms_purchase/README.rst
  pms_purchase/__init__.py
  pms_purchase/__manifest__.py
  pms_purchase/models/__init__.py
  pms_purchase/models/pms_property.py
  pms_purchase/models/purchase_order_line.py
  pms_purchase/models/stock_move.py
  pms_purchase/models/stock_putaway_rule.py
  pms_purchase/readme/CONFIGURATION.rst
  pms_purchase/readme/CONTRIBUTORS.rst
  pms_purchase/readme/DESCRIPTION.rst
  pms_purchase/readme/USAGE.rst
  pms_purchase/static/description/icon.png
  pms_purchase/static/description/index.html
  pms_purchase/tests/__init__.py
  pms_purchase/tests/test_pms_property.py
  pms_purchase/tests/test_purchase.py
  pms_purchase/tests/test_putaway_method.py
  pms_purchase/views/pms_property.xml
  pms_purchase/views/purchase_order.xml
  pms_purchase/views/stock_putaway_views.xml
  setup/pms_purchase/odoo/addons/pms_purchase
  setup/pms_purchase/setup.py
Labels: enhancement

#143 [IMP]pms: Improvemente relation amount pending folio and payments wit…
  pms/models/account_payment.py
  pms/models/pms_folio.py
  pms/views/folio_portal_templates.xml
  pms/views/pms_folio_views.xml
  pms/wizards/folio_make_invoice_advance.py
Labels: bot is merging ⏳

#93 [ADD] pms_website_sale
  pms_website_sale/README.rst
  pms_website_sale/__init__.py
  pms_website_sale/__manifest__.py
  pms_website_sale/controllers/__init__.py
  pms_website_sale/controllers/website.py
  pms_website_sale/data/website_menu.xml
  pms_website_sale/i18n/es.po
  pms_website_sale/i18n/pms_website_sale.pot
  pms_website_sale/readme/CONFIGURE.rst
  pms_website_sale/readme/CONTRIBUTORS.rst
  pms_website_sale/readme/DESCRIPTION.rst
  pms_website_sale/readme/USAGE.rst
  pms_website_sale/security/ir.model.access.csv
  pms_website_sale/security/pms_website_sale.xml
  pms_website_sale/static/description/index.html
  pms_website_sale/static/src/js/pms_property.js
  pms_website_sale/static/tests/tours/pms_website_sale_tour.js
  pms_website_sale/tests/__init__.py
  pms_website_sale/tests/test_pms_sale_property.py
  pms_website_sale/views/assets.xml
  pms_website_sale/views/templates.xml
  setup/pms_website_sale/odoo/addons/pms_website_sale
  setup/pms_website_sale/setup.py
Labels: enhancement

#142 [IMP]pms: added demo data pricelist items and availability plan rules
  pms/demo/pms_master_data.xml
Labels: bot is merging ⏳

#146 [IMP]pms: refact compute folio sale lines
  pms/demo/pms_master_data.xml
  pms/models/folio_sale_line.py
  pms/models/pms_availability_plan.py
  pms/models/pms_checkin_partner.py
  pms/models/pms_folio.py
  pms/models/pms_reservation.py
  pms/models/pms_reservation_line.py
  pms/tests/test_pms_availability_plan_rules.py
  pms/tests/test_product_template.py
  pms/views/pms_folio_views.xml
Labels: bot is merging ⏳

#145 [FIX] pms_sale: Checkout time on reservation wizard
  pms_sale/wizards/pms_configurator.py
Labels: bug, needs review
