Repository OCA/pms, pull requests merged in 2022-02, with the labels that each got.

#87 [ADD] pms_account
  pms_account/README.rst
  pms_account/__init__.py
  pms_account/__manifest__.py
  pms_account/i18n/es.po
  pms_account/i18n/pms_account.pot
  pms_account/models/__init__.py
  pms_account/models/account_move.py
  pms_account/models/account_move_line.py
  pms_account/models/pms_property.py
  pms_account/models/pms_service.py
  pms_account/readme/CONFIGURE.rst
  pms_account/readme/CONTRIBUTORS.rst
  pms_account/readme/DESCRIPTION.rst
  pms_account/readme/USAGE.rst
  pms_account/static/description/agency_logo.png
  pms_account/static/description/agency_logo1.png
  pms_account/static/description/avatar.png
  pms_account/static/description/icon.png
  pms_account/static/description/index.html
  pms_account/views/account_move.xml
  pms_account/views/pms_property.xml
  setup/pms_account/odoo/addons/pms_account
  setup/pms_account/setup.py
Labels: enhancement, needs review, bot is merging ⏳

#117 [FIX] pms_base
  pms_base/__manifest__.py
Labels: bug, bot is merging ⏳

#88 [ADD] pms_account_asset
  oca_dependencies.txt
  pms_account_asset/README.rst
  pms_account_asset/__init__.py
  pms_account_asset/__manifest__.py
  pms_account_asset/i18n/es.po
  pms_account_asset/i18n/pms_account_asset.pot
  pms_account_asset/models/__init__.py
  pms_account_asset/models/account_asset.py
  pms_account_asset/models/pms_property.py
  pms_account_asset/readme/CONFIGURE.rst
  pms_account_asset/readme/CONTRIBUTORS.rst
  pms_account_asset/readme/DESCRIPTION.rst
  pms_account_asset/readme/USAGE.rst
  pms_account_asset/static/description/icon.png
  pms_account_asset/static/description/index.html
  pms_account_asset/views/account_asset.xml
  pms_account_asset/views/menu.xml
  pms_account_asset/views/pms_property.xml
  setup/pms_account_asset/odoo/addons/pms_account_asset
  setup/pms_account_asset/setup.py
Labels: enhancement, needs review, bot is merging ⏳

#91 [ADD] pms_crm
  pms_crm/README.rst
  pms_crm/__init__.py
  pms_crm/__manifest__.py
  pms_crm/i18n/es.po
  pms_crm/i18n/pms_crm.pot
  pms_crm/models/__init__.py
  pms_crm/models/crm_lead.py
  pms_crm/models/pms_property.py
  pms_crm/readme/CONTRIBUTORS.rst
  pms_crm/readme/DESCRIPTION.rst
  pms_crm/readme/USAGE.rst
  pms_crm/static/description/icon.png
  pms_crm/static/description/index.html
  pms_crm/views/crm_lead.xml
  pms_crm/views/pms_property.xml
  setup/pms_crm/odoo/addons/pms_crm
  setup/pms_crm/setup.py
Labels: enhancement, needs review, bot is merging ⏳

#116 [14.0] [ADD] pms: add demo data & fix some issues with reservation states
  pms/data/pms_data.xml
  pms/demo/airbnb-logo.jpg
  pms/demo/booking-logo.jpg
  pms/demo/pms_folio.xml
  pms/demo/pms_master_data.xml
  pms/demo/pms_reservation.xml
  pms/models/pms_checkin_partner.py
  pms/models/pms_reservation.py
  pms/static/description/agency_logo.png
  pms/static/description/agency_logo1.png
Labels: approved, bot is merging ⏳

#121 [FIX] pms_base
  pms_base/models/pms_stage.py
  pms_base/models/pms_tag.py
  pms_base/models/pms_team.py
Labels: bug, needs review, bot is merging ⏳

#115 [REF]pms: refactor precheckin
  pms/controllers/pms_portal.py
  pms/data/pms_precheckin_invitation_email_template.xml
  pms/i18n/es.po
  pms/models/pms_checkin_partner.py
  pms/tests/test_pms_checkin_partner.py
  pms/views/precheckin_portal_templates.xml
Labels: bot is merging ⏳

#118 [14.0] [IMP] pms_l10n_es: Throw an exception if generating the ine statistic…
  pms_l10n_es/tests/test_wizard_ine.py
  pms_l10n_es/wizards/wizard_ine.py
Labels: bot is merging ⏳

#114 [14.0][FIX] pms: calculation of folio commission
  pms/models/pms_folio.py
  pms/models/pms_reservation.py
  pms/tests/test_pms_folio.py
  pms/tests/test_pms_reservation.py
Labels: bot is merging ⏳

#122 [WIP]14.0 pms refactor email
  pms/data/pms_cancelled_reservation_email_template.xml
  pms/data/pms_confirmed_reservation_email_template.xml
  pms/data/pms_modified_reservation_email_template.xml
  pms/models/mail_compose_message.py
  pms/models/pms_folio.py
  pms/models/pms_reservation.py
  pms/views/pms_reservation_views.xml
Labels: bot is merging ⏳
